name: Cpoy

on:
  workflow_dispatch:

jobs:
  download-and-add-multiple-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: Repcz/Open-Profiles
        path: open-profiles-repo

    - name: Create target directory
      run: |
        mkdir -p open-profiles-repo/Rules
        ls -R open-profiles-repo/Rules
    
    - name: Download and add files
      run: |
        files=(
          "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
          "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
          # Add more URLs here
        )
        
        for url in "${files[@]}"; do
          filename=$(basename "$url")
          curl -L -o "open-profiles-repo/Rules/$filename" "$url"
        done
    
    - name: Add and Commit
      run: |
        cd open-profiles-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Rules/*
        git commit -m "Add multiple files"
        git push origin HEAD
